### PR TITLE
Upgrade zk 3.5 to run on java 11

### PR DESCRIPTION
**Pull request by amuraru**

### CODE REVIEW

**Comment by 31z4** [comment]
Could you please explain what are the benefits of upgrading to java 11?

**Comment by amuraru** [comment]
Java egonomics were improved in v11. Eg: correctly reads the cpu cores limit when run in containers (docker, kubernetes), auto-tunes the GC based on container mem/cpu limits. Plus zookeeper now supports java 11

**Comment by 31z4** [comment]
@amuraru do you have any confirmation if OpenJDK 11 is supported by the upstream? Especially the `3.4` branch.

I personally couldn't find any strong evidence of that at the moment, except this thread: http://zookeeper-user.578899.n2.nabble.com/Java-11-OpenJDK-Oracle-Java-Release-Cadence-Questions-td7583852.html

**Comment by amuraru** [comment]
zk builds are maintained in apache jenkins: https://builds.apache.org/view/ZK%20All/
Latest release of 3.4 passed on java11:
 https://builds.apache.org/view/ZK%20All/job/ZooKeeper_branch34_java11/591/console

**Comment by amuraru** [comment]
For extra safety I would keep zk 3.4 on java8 https://github.com/31z4/zookeeper-docker/blob/master/3.4.14/Dockerfile#L1 and integrate this patch only where only zk 3.5 is upgraded to run on java11

**Comment by 31z4** [comment]
@amuraru please rebase and I'm ready to merge it 🙂

**Comment by amuraru** [comment]
@31z4 done - thanks

**Pull request merged**
