### PR TITLE
Remove Zookeeper 3.3.6 

### PR DESCRIPTION
**Pull request by dustinschultz**
3.3.6 distro doesn't exist at https://www.apache.org/dist anymore, only at https://archive.apache.org/dist

### CODE REVIEW

**Comment by tianon** [comment]
Is 3.3 still even supported?  It seems like it was moved to archive.apache.org because it's EOL, in which case I think removing it here is probably more appropriate, right?

Removing it here (and in `library/zookeeper`) will remove it from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding it on the official build server), but the tag will still be available to users who want it.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by dustinschultz** [comment]
Good question ... I can't find anything that explicitly says it's EOL. It has only been moved to "old versions". 

The zookeeper JIRA has a 3.3.7 fix version with some issues in it but I don't see any tags related to it and the issues in it are from 2012. 

I'd be +1 for removing it.

**Comment by 31z4** [comment]
`3.3.6` hasn't been updated in two years. I think we're safe to remove.

**Comment by dustinschultz** [comment]
👍 - PR has been updated to remove 3.3.6

**Comment by 31z4** [comment]
Thanks!

**Pull request merged**
