### PR TITLE
add support for advanced configuration via ENV

### PR DESCRIPTION
**Pull request by smcavallo**
https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_advancedConfiguration

Add ability to set all existing advanced configuration options via ENV

### CODE REVIEW

**Comment by duncaan** [comment]
@31z4 can you please review this?

**Comment by 31z4** [comment]
The idea of having several configuration options as ENV variables is to facilitate tweaking some often changing options and options related to the replicated mode. There's [a way](https://github.com/31z4/zookeeper-docker#configuration) to mount a custom configuration file for other cases.

Thus, don't think the advanced configuration should be exposed via ENV.

**Comment by duncaan** [comment]
The problem @smcavallo is addressing with this pull request is to be able to be able to use environment variables without having to mount a file and lose any defaults that are set. Why provide less configuration options?

**Comment by smcavallo** [comment]
@31z4 - for ease of use for us, it would be great to support more options via ENV instead of needing to volume mount a config file.   Additionally, it could enable us to deploy zookeeper to ECR and platforms which don't support volume mounts and where the only configuration option is ENV.

**Comment by 31z4** [comment]
I added a section describing advanced configuration to the image documentation. See [this PR](https://github.com/docker-library/docs/pull/1715).

Hope that helps 🙂

**Pull request closed without merging**
