### PR TITLE
Upgrade to JRE 17, and pin Ubuntu on jammy

### LINKED ISSUE #143: Upgrade to JRE 17, pin Ubuntu release
JRE11 is end of life. Upgrade to 17 in the image.

In the Solr project we recently started pinning Linux/Ubuntu version of our images, since the `eclipse-temurin:jre-xx` base images gets auto updated on new ubuntu major releases. We chose to pin to Ubuntu "focal" release for max compatibility, see https://solr.apache.org/news#solr-docker-images-now-pin-the-linux-release and https://github.com/apache/solr-docker/pull/13

We should pin ubuntu release as "jammy", and do an active choice to bump it at a later time.

### PR DESCRIPTION
**Pull request by janhoy**
Fixes #143

### CODE REVIEW

**Comment by 31z4** [comment]
Hi @janhoy, thanks for your interest in contributing to Zookeeper Docker image! Do you know if 3.7 and 3.8 are compatible with JRE 17? If it is then I think we should pin these versions as well.

**Comment by janhoy** [comment]
Yes, all versions support JDK 17, updated. Will try to get my commit signed...

**Comment by 31z4** [comment]
Looks good, merging 👍

**Comment by 31z4** [comment]
I added separate tags for JRE 17 to help users migrate and avoid possible compatibility issues: https://github.com/docker-library/official-images/pull/1554

**Pull request merged**
