### PR TITLE
Add client address since it defaults to 0.0.0.0

### PR DESCRIPTION
**Pull request by MAHashmi**

### CODE REVIEW

**Comment by MAHashmi** [comment]
Referencing the documentation, the client address defaults to 0.0.0.0 for all servers. 
Screen Shot 2019-11-06 at 16 42 52

**Comment by 31z4** [comment]
Sorry, `31z4/zookeeper` is no longer maintained. I updated [README.md](https://github.com/31z4/zookeeper-docker/blob/master/README.md) to avoid confusion.

Could you please elaborate if this change fixes any issue you're facing?

**Comment by MAHashmi** [comment]
I was could see error messages in zookeeper about not being able to connect to one of the nodes. The error messages suggested that the particular node was down. Additionally if I tried to connect to each of the nodes individually with zkCli, I was randomly unable to connect to at least one node all the time. After I provided the explicit client address, it was fixed.

**Comment by 31z4** [comment]
Image documentation is no longer a part of that repo. Please feel free to contribute to https://github.com/docker-library/docs/blob/master/zookeeper/content.md

**Pull request closed without merging**
